export const FRAMEWORK_META = {
  EU_AI_ACT: {
    name: "EU AI Act",
    description: "European regulation on artificial intelligence systems",
    icon: "🤖",
    color: "blue",
    estimatedControls: 30,
    certificationBody: "Notified Body / Internal",
  },
  GDPR: {
    name: "GDPR",
    description: "General Data Protection Regulation",
    icon: "🔒",
    color: "green",
    estimatedControls: 30,
    certificationBody: "Supervisory Authority",
  },
  ISO_27001: {
    name: "ISO 27001",
    description: "Information Security Management System",
    icon: "🛡️",
    color: "purple",
    estimatedControls: 114,
    certificationBody: "Accredited Certification Body",
  },
  SOC2: {
    name: "SOC 2",
    description: "Service Organization Control 2",
    icon: "✅",
    color: "indigo",
    estimatedControls: 60,
    certificationBody: "AICPA-Licensed CPA Firm",
  },
  NIS2: {
    name: "NIS2",
    description: "Network and Information Security Directive 2",
    icon: "🌐",
    color: "cyan",
    estimatedControls: 15,
    certificationBody: "National Authority",
  },
  DORA: {
    name: "DORA",
    description: "Digital Operational Resilience Act",
    icon: "⚡",
    color: "orange",
    estimatedControls: 20,
    certificationBody: "Financial Supervisory Authority",
  },
  CYBER_RESILIENCE_ACT: {
    name: "Cyber Resilience Act",
    description: "EU cybersecurity requirements for products with digital elements",
    icon: "🔐",
    color: "red",
    estimatedControls: 12,
    certificationBody: "Notified Body",
  },
} as const;
