export const ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  ONBOARDING: "/onboarding",
  DASHBOARD: "/dashboard",
  FRAMEWORKS: "/frameworks",
  SCAN: "/scan",
  EVIDENCE: "/evidence",
  RISK: "/risk",
  POLICIES: "/policies",
  VENDORS: "/vendors",
  INTEGRATIONS: "/integrations",
  TEAM: "/team",
  REPORTS: "/reports",
  AI_ASSISTANT: "/ai-assistant",
  SETTINGS: "/settings",
  BILLING: "/settings/billing",
  PRICING: "/pricing",
} as const;
